apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: preprocess
  name: mobilenet-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilenet-v1
  template:
    metadata:
      labels:
        app: mobilenet-v1
    spec:
      containers:
        - name: mobilenet-v1
          image: public.ecr.aws/f4b9d0l0/swarch-23-2-preprocess-mobilenet_v1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: preprocess
  name: mobilenet-v1
spec:
  type: ClusterIP
  selector:
    app: mobilenet-v1
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080