---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: inference
  name: inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - name: inference
          image: kmubigdata/tfserving-armv8:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: inference
  name: inference-service
spec:
  type: ClusterIP
  selector:
    app: inference
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080