---
apiVersion: v1
kind: Namespace
metadata:
  name: postprocess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: postprocess
  name: postprocess-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postprocess
  template:
    metadata:
      labels:
        app: postprocess
    spec:
      containers:
        - name: postprocess
          image: public.ecr.aws/f4b9d0l0/swarch-23-2-postprocess-mobilenet_v1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: postprocess
  name: postprocess-service
spec:
  type: ClusterIP
  selector:
    app: postprocess
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8080