---
apiVersion: v1
kind: Namespace
metadata:
  name: preprocess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: preprocess
  name: preprocess-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocess
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
        - name: preprocess
          image: public.ecr.aws/f4b9d0l0/swarch-23-2-preprocess-mobilenet_v1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: preprocess
  name: preprocess-service
spec:
  type: ClusterIP
  selector:
    app: preprocess
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080