apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: inference
  name: yolo-v5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-v5
  template:
    metadata:
      labels:
        app: yolo-v5
    spec:
      containers:
        - name: yolo-v5
          image: public.ecr.aws/f4b9d0l0/swarch-23-2-inference-yolo_v5:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: inference
  name: yolo-v5
spec:
  type: ClusterIP
  selector:
    app: yolo-v5
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080