FROM swarch-23-2-ml-rest-docker-base

WORKDIR /app

COPY ./models/mobilenet_v1 /app/mobilenet_v1

COPY ./build_assets/mobilenet_v1/rest_main.py /app

EXPOSE 8501

CMD ["uvicorn", "rest_main:app", "--port", "8501", "--host", "0.0.0.0"]

